@echo off
cd /d "%~dp0"

set OCR_PROVIDER=qwen3-vl
set POSTPROCESSOR_PROVIDER=symspell

set OCR_CONFIG__PROVIDER_VERSION=contract-1.0.0
set OCR_CONFIG__LOCAL_FILES_ONLY=true
set OCR_CONFIG__ALLOW_CPU_FALLBACK=true
set OCR_CONFIG__DTYPE=bfloat16
set OCR_CONFIG__BATCH_SIZE=1
set OCR_CONFIG__MAX_IMAGE_SIZE=1024
set OCR_CONFIG__MAX_PAGES=10
set OCR_CONFIG__PDF_RENDER_DPI=144
set OCR_CONFIG__TIMEOUT_SECONDS=300
set OCR_CONFIG__MAX_NEW_TOKENS=512
set OCR_CONFIG__DO_SAMPLE=false
set OCR_CONFIG__TEMPERATURE=0.1
set OCR_CONFIG__TOP_P=1.0
set OCR_CONFIG__NUM_BEAMS=1
set OCR_CONFIG__PROMPT=Transcribe the medical document exactly, preserving reading order.
set OCR_CONFIG__PROMPT_VERSION=deployment-approved-v1
set OCR_CONFIG__CONFIDENCE_THRESHOLD=0.60
set OCR_CONFIG__CONFIDENCE_CALIBRATION_VERSION=token-probability-uncalibrated-v1
set OCR_CONFIG__SEED=0

set POSTPROCESSOR_CONFIG__PROVIDER_VERSION=contract-1.0.0
set POSTPROCESSOR_CONFIG__DICTIONARY_PATH=%~dp0tests\ocr\fixtures\symspell_frequency.txt
set POSTPROCESSOR_CONFIG__DICTIONARY_VERSION=deployment-approved-v1
set POSTPROCESSOR_CONFIG__ABBREVIATION_DICTIONARY_PATH=%~dp0tests\ocr\fixtures\medical_abbreviations.json
set POSTPROCESSOR_CONFIG__ABBREVIATION_DICTIONARY_VERSION=deployment-approved-v1
set POSTPROCESSOR_CONFIG__PROTECTED_TERMS_PATH=%~dp0tests\ocr\fixtures\protected_medical_terms.json
set POSTPROCESSOR_CONFIG__RULE_VERSION=deployment-approved-v1
set POSTPROCESSOR_CONFIG__MAX_EDIT_DISTANCE=2
set POSTPROCESSOR_CONFIG__PREFIX_LENGTH=7
set POSTPROCESSOR_CONFIG__MIN_WORD_LENGTH=4
set POSTPROCESSOR_CONFIG__MIN_FREQUENCY=1

".venv\Scripts\python.exe" -m uvicorn app.main:app --host 127.0.0.1 --port 8000
