# Local engineering-demo launcher. Uses synthetic/test post-processing dictionaries only.
$ErrorActionPreference = "Stop"
$demoRoot = $PSScriptRoot

$env:OCR_PROVIDER = "qwen3-vl"
$env:POSTPROCESSOR_PROVIDER = "symspell"
$env:OCR_CONFIG__PROVIDER_VERSION = "mvp-1.0.0"
$env:OCR_CONFIG__MODEL_NAME = "Qwen/Qwen3-VL-4B-Instruct"
$env:OCR_CONFIG__MODEL_REVISION = "ebb281ec70b05090aa6165b016eac8ec08e71b17"
$env:OCR_CONFIG__HF_CACHE_DIR = Join-Path $demoRoot ".model-cache/qwen3-vl"
$env:OCR_CONFIG__LOCAL_FILES_ONLY = "true"
$env:OCR_CONFIG__DEVICE = "cpu"
$env:OCR_CONFIG__ALLOW_CPU_FALLBACK = "true"
$env:OCR_CONFIG__DTYPE = "float32"
$env:OCR_CONFIG__BATCH_SIZE = "1"
$env:OCR_CONFIG__MAX_IMAGE_SIZE = "1024"
$env:OCR_CONFIG__MAX_PAGES = "10"
$env:OCR_CONFIG__PDF_RENDER_DPI = "96"
$env:OCR_CONFIG__TIMEOUT_SECONDS = "120"
$env:OCR_CONFIG__MAX_NEW_TOKENS = "512"
$env:OCR_CONFIG__DO_SAMPLE = "false"
$env:OCR_CONFIG__TEMPERATURE = "0.1"
$env:OCR_CONFIG__TOP_P = "1.0"
$env:OCR_CONFIG__NUM_BEAMS = "1"
$env:OCR_CONFIG__PROMPT = "Transcribe the medical document exactly and return the configured structured output."
$env:OCR_CONFIG__PROMPT_VERSION = "mvp-prompt-v1"
$env:OCR_CONFIG__CONFIDENCE_THRESHOLD = "0.60"
$env:OCR_CONFIG__CONFIDENCE_CALIBRATION_VERSION = "token-probability-uncalibrated-v1"
$env:OCR_CONFIG__SEED = "0"

$fixtureRoot = Join-Path $demoRoot "tests/ocr/fixtures"
$env:POSTPROCESSOR_CONFIG__PROVIDER_VERSION = "mvp-1.0.0"
$env:POSTPROCESSOR_CONFIG__DICTIONARY_PATH = Join-Path $fixtureRoot "symspell_frequency.txt"
$env:POSTPROCESSOR_CONFIG__DICTIONARY_VERSION = "mvp-fixture-v1"
$env:POSTPROCESSOR_CONFIG__ABBREVIATION_DICTIONARY_PATH = Join-Path $fixtureRoot "medical_abbreviations.json"
$env:POSTPROCESSOR_CONFIG__ABBREVIATION_DICTIONARY_VERSION = "mvp-fixture-v1"
$env:POSTPROCESSOR_CONFIG__PROTECTED_TERMS_PATH = Join-Path $fixtureRoot "protected_medical_terms.json"
$env:POSTPROCESSOR_CONFIG__RULE_VERSION = "mvp-rules-v1"
$env:POSTPROCESSOR_CONFIG__MAX_EDIT_DISTANCE = "2"
$env:POSTPROCESSOR_CONFIG__PREFIX_LENGTH = "7"
$env:POSTPROCESSOR_CONFIG__MIN_WORD_LENGTH = "4"
$env:POSTPROCESSOR_CONFIG__MIN_FREQUENCY = "1"

$env:REPORT_QWEN_SIMPLIFIER_ENABLED = "true"
$env:SIMPLIFICATION_CONFIG__DEVICE = "cpu"
$env:SIMPLIFICATION_CONFIG__COMPILE = "false"
$env:SIMPLIFICATION_CONFIG__MAX_NEW_TOKENS = "384"
$env:SIMPLIFICATION_CONFIG__MAX_INPUT_CHARACTERS = "12000"

Set-Location -LiteralPath $demoRoot
& (Join-Path $demoRoot ".venv/Scripts/python.exe") -m uvicorn app.main:app --host 127.0.0.1 --port 8000
